---
inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - examples/**/*
    - gemfiles/**/*
    - spec/dummy/**/*
    - vendor/**/*
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Naming/FileName:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120

RSpec/ExampleLength:
  Max: 8

RSpec/MultipleExpectations:
  Max: 5

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
