---
inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - examples/**/*
    - gemfiles/**/*
    - spec/dummy/**/*
    - vendor/**/*
  NewCops: enable

Style/OpenStructUse:
  Enabled: false # TODO: fix me

RSpec/ExampleLength:
  # default 5
  Max: 10
